---
- hosts: redis
  become: yes

  tasks:

    - name: Copy bundle
      copy:
        src: /home/naveen_manuri/redis/redis-offline-bundle.tar.gz
        dest: /tmp/redis-offline-bundle.tar.gz

    - name: Create folder
      file:
        path: /tmp/redisbundle
        state: directory

    - name: Extract bundle
      unarchive:
        src: /tmp/redis-offline-bundle.tar.gz
        dest: /tmp/redisbundle
        remote_src: yes

    - name: Install all deb packages
      shell: dpkg -i /tmp/redisbundle/*.deb || apt-get install -f -y

    # ---------------- MASTER INSTANCE ----------------

    - name: Create master directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/redis-master
        - /var/lib/redis-master
        - /var/log/redis-master

    - name: Configure Redis Master
      copy:
        dest: /etc/redis-master/redis.conf
        content: |
          bind 0.0.0.0
          protected-mode no
          port 6379
          daemonize yes
          pidfile /var/run/redis-master.pid
          logfile /var/log/redis-master/redis.log
          dir /var/lib/redis-master

          cluster-enabled yes
          cluster-config-file nodes-6379.conf
          cluster-node-timeout 5000
          appendonly yes

    # ---------------- SLAVE INSTANCE ----------------

    - name: Create slave directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/redis-slave
        - /var/lib/redis-slave
        - /var/log/redis-slave

    - name: Configure Redis Slave
      copy:
        dest: /etc/redis-slave/redis.conf
        content: |
          bind 0.0.0.0
          protected-mode no
          port 7000
          daemonize yes
          pidfile /var/run/redis-slave.pid
          logfile /var/log/redis-slave/redis.log
          dir /var/lib/redis-slave

          cluster-enabled yes
          cluster-config-file nodes-7000.conf
          cluster-node-timeout 5000
          appendonly yes

    # ---------------- START SERVICES ----------------

    - name: Stop default redis service
      service:
        name: redis-server
        state: stopped
      ignore_errors: yes

    - name: Start master instance
      shell: redis-server /etc/redis-master/redis.conf

    - name: Start slave instance
      shell: redis-server /etc/redis-slave/redis.conf
