[redis]
vm1 ansible_host=10.30.1.60
vm2 ansible_host=10.30.1.61
vm3 ansible_host=10.30.1.62

[redis:vars]
ansible_user=redhat
ansible_ssh_private_key_file=/home/naveen_manuri/.ssh/id_ed25519
ansible_become=yes
ansible_become_method=sudo
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
